version: '3'
services:
  database:
    image: mysql:8
    container_name: mysqldb
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devopstpachat
    ports:
      - 3306:3306
    networks:
      - devopstp
  

  spring-boot:
    image: muckydreamz/tpachatdevops
    container_name: spring
    ports:
      - 8089:8089
    depends_on:
      - database
    networks:
      - devopstp
    restart: on-failure

networks:
  devopstp:
