version: '3'
services:

  database:
    image: mysql:8
    container_name: mysqldb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devopstpachat
    volumes:
      - /home/mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - devopstp

  spring-boot:
    image: muckydreamz/tpachatdevops
    container_name: spring
    ports:
      - 8089:8089
    depends_on:
      - database
    networks:
      - devopstp
    restart: on-failure
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:mysql://mysql:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
            "spring.datasource.username" : "$MYSQLDB_USER",
            "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
            "spring.jpa.hibernate.ddl-auto" : "update"
          }'

  angular:
    image: muckydreamz/devopsfront:13
    container_name: angular
    ports:
      - 88:88
    depends_on:
      - spring-boot
    networks:
      - devopstp

networks:
  devopstp: